version: '3.8'

services:
  gtts-api:
    build: .
    container_name: gtts-fastapi
    ports:
      - "${GTTS_PORT:-8088}:8000"
    restart: unless-stopped
    environment:
      - PORT=8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

