version: '3.8'

services:
  # The API service to test against (optional - can test against host)
  api:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: gtts-api-test
    ports:
      - "8088:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    networks:
      - test-network
    profiles:
      - with-api  # Only start if explicitly requested

  # The test runner - can test against host machine or api service
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gtts-tests
    environment:
      # Default: test against host machine's localhost
      # Use host.docker.internal to reach host from Docker on Mac/Windows
      # On Linux, use --add-host=host.docker.internal:host-gateway
      - API_HOST=${API_HOST:-host.docker.internal}
      - API_PORT=${API_PORT:-8088}
    volumes:
      - ./reports:/app/testing/reports
    extra_hosts:
      # For Linux: allow accessing host machine
      - "host.docker.internal:host-gateway"
    networks:
      - test-network
    command: >
      sh -c "pytest ${PYTEST_ARGS:--v} --html=reports/test-report.html --self-contained-html"

networks:
  test-network:
    driver: bridge

